# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 411d273f2108268ee9fb8f3f84bd3d0357f2f7fc155cba1bdaa11eb0f490ce4ba832bfa5f394ba9a9c7d6a20d460d3d86367620303fa9b5eb1ce09bc06b681d8

test:
  secret_key_base: c381a173cfcb8e791f8dfcc3effaef70f441a3032a38dee8b62e72e5352542a45d64f89397dacb8d1bf6b69bb74363aa8d405218116e065d039ae03094fd460f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
